language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install: 
  - python setup.py install
  - pip install future
  - pip install coveralls
script: nosetests
after_success: coveralls
notifications:
  email: false